commit_message: '[Localization] Update %language% translations'
append_commit_message: false
files:
  - source: /Zebra/Base.lproj/Localizable.strings
    translation: /Zebra/%osx_code%/Localizable.strings
